#!/bin/bash

echo "=========================================="
echo "GitHub Pages Custom URL Setup"
echo "=========================================="
echo ""
echo "You have two options:"
echo ""
echo "OPTION 1: Create GitHub Organization (FREE)"
echo "  - Create organization: support-mgnrega"
echo "  - Create repo: support-mgnrega.github.io"
echo "  - Result: https://support-mgnrega.github.io"
echo ""
echo "OPTION 2: Use Custom Domain"
echo "  - Buy domain (e.g., support-mgnrega.com)"
echo "  - Configure DNS"
echo "  - Add CNAME file"
echo "  - Result: https://support-mgnrega.com"
echo ""
echo "See CUSTOM_DOMAIN_SETUP.md for detailed instructions"
echo ""
